const SET_LOADER = 'SET_LOADER';
const SET_ERROR = 'SET_ERROR';
const REMOVE_LOADER = 'REMOVE_LOADER';
const FETCH_WEATHER = 'FETCH_WEATHER';

export {
    SET_LOADER,
    REMOVE_LOADER,
    SET_ERROR,
    FETCH_WEATHER
}